export const responseMock = {
	results: {
		isGooglePowered: false,
		docs: [
			{
				country: 'Portugal',
				lng: -9.12956,
				city: 'Lisbon',
				searchType: 'L',
				alternative: ['PT,Estremadura,Portela'],
				index: 1,
				bookingId: 'airport-28061',
				placeType: 'A',
				placeKey: '1472612',
				iata: 'LIS',
				countryIso: 'pt',
				locationId: '28061',
				name: 'Lisbon Airport',
				ufi: 900038576,
				isPopular: true,
				region: 'Lisbon Region',
				lang: 'en',
				lat: 38.7704,
			},
			{
				country: 'Portugal',
				lng: -9.13931,
				searchType: 'L',
				alternative: ['PT'],
				index: 2,
				bookingId: 'city-1991509',
				placeType: 'C',
				placeKey: '1046437',
				countryIso: 'pt',
				locationId: '16511',
				name: 'Lisbon',
				ufi: -2167973,
				isPopular: false,
				region: 'Região de Lisboa',
				lang: 'en',
				lat: 38.7138,
			},
			{
				country: 'Portugal',
				lng: -9.13931,
				searchType: 'L',
				alternative: ['PT'],
				index: 2,
				bookingId: 'station-1991509',
				placeType: 'T',
				placeKey: '1046437',
				countryIso: 'pt',
				locationId: '16511',
				name: 'Lisbon',
				ufi: -2167973,
				isPopular: false,
				region: 'Região de Lisboa',
				lang: 'en',
				lat: 38.7138,
			},
			{
				country: 'Portugal',
				lng: -9.13931,
				searchType: 'L',
				alternative: ['PT'],
				index: 2,
				bookingId: 'Region-1991509',
				placeType: 'P',
				placeKey: '1046437',
				countryIso: 'pt',
				locationId: '16511',
				name: 'Lisbon',
				ufi: -2167973,
				isPopular: false,
				region: 'Região de Lisboa',
				lang: 'en',
				lat: 38.7138,
			},
			{
				country: 'Portugal',
				lng: -9.13931,
				searchType: 'L',
				alternative: ['PT'],
				index: 2,
				bookingId: 'district-1991509',
				placeType: 'D',
				placeKey: '1046437',
				countryIso: 'pt',
				locationId: '16511',
				name: 'Lisbon',
				ufi: -2167973,
				isPopular: false,
				region: 'Região de Lisboa',
				lang: 'en',
				lat: 38.7138,
			},
		],
		numFound: 609,
	},
};

export const noResultsResposeMock = {
	results: {
		isGooglePowered: false,
		docs: [
			{
				name: 'No results found',
				index: 1,
			},
		],
		numFound: 0,
	},
};
